init java project
Super-Patos-Hackaton/backend pull request #1
Opened 2024-06-14 13:10 UTC by Gabriel-Santiago

## Description

## Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Enhancements

## Checklist
- [ ] Documentation has been added or updated (if applicable)

2024-06-14 13:40 UTC, Luiz-AVcruz requested changes
Os arquivos do projeto estão dentro de uma pasta. Por favor, mover todos os arquivos para a raiz do repositório.

2024-06-14 16:03 UTC, Luiz-AVcruz submitted a review, later dismissed
lgtm

2024-06-18 02:32 UTC, FelipeMartinsFrudeli approved these changes, later dismissed

2024-06-18 10:08 UTC, gustavocarl approved these changes

2024-06-18 19:58 UTC, RO-HSA approved these changes
LGTM

2024-06-18 19:59 UTC, merged

2024-06-18 20:01 UTC, thaleson reviewed
approved t